packages:
  - apps/*
  - packages/*
allowBuilds:
  "@nestjs/core": true
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
nodeLinker: hoisted
storeDir: .pnpm-store
strictDepBuilds: false
