export const APPLICATION_SERVICE = Symbol("APPLICATION_SERVICE");
export const ARTIFACT_PIPELINE = Symbol("ARTIFACT_PIPELINE");
export const ARTIFACT_STORAGE = Symbol("ARTIFACT_STORAGE");
export const ARTIFACT_MAX_SIZE_BYTES = Symbol("ARTIFACT_MAX_SIZE_BYTES");
export const APPLICATION_UPLOAD_SERVICE = Symbol("APPLICATION_UPLOAD_SERVICE");
