local   all             all                                      peer
host    all             all             10.20.0.0/24             scram-sha-256
host    replication     replicator      10.20.0.0/24             scram-sha-256
