listen_addresses = '*'
wal_level = replica
max_wal_senders = 10
max_replication_slots = 2
wal_keep_size = '1024MB'
archive_mode = on
archive_timeout = '60s'
archive_command = 'test ! -f /var/lib/postgresql/wal-archive/%f && cp %p /var/lib/postgresql/wal-archive/%f'
hot_standby = off
hba_file = '/etc/postgresql/pg_hba.production.conf'
